### ISSUE TITLE
Send hash with dynamic attributes in params.

### ISSUE THREAD

**Issue by svanegas** [tim-vandecasteele/grape-swagger#282] opened 2015-07-30 18:08 UTC
Hi, I'm trying to send a hash with attributes that are not defined in a post method. I need to do that like a metadata field. This is my code:

```ruby
module MyApp
  module V1
    module Foo
      class Root < Grape::API

        desc 'test for hash'
        params do
          requires :metadata, type: Hash
        end
        post do
          present "GOT: #{params[:metadata].to_json}"
        end
      end
    end
  end
end
```

Which generates the following view.
![swagger-generated](http://i.imgur.com/aWcRwhg.png)

Notice that I'm not restricting the hash to have specific nested attributes, so that I can send any parameter inside the *'metadata'* field and **handle it as JSON** inside my application, as follows:

`{"metadata": {"color": "blue"}}`

When I try to put some value in the metadata field I always get *'metadata is invalid'* as error.

![swagger-generated](http://i.imgur.com/PmyfkCL.png)

I did the same request via *Postman* and using *cURL* and it works nice.  
```sh
$ curl -X POST -d '{"metadata": {"color": "blue"}}' http://localhost:3000/api/v1/foo.json -H 'Content-Type:application/json'
 > "GOT: {\"color\":\"blue\"}"
$
```

The idea is that the user may send any information in *'metadata'* field as a JSON, or Hash. Could you guys help me to achieve that?

**Comment by dblock** [comment] 2015-07-31 12:51
So it works with curl, but not in swagger UI? Use a JavaScript console in the browser, what's swagger UI posting in this case?

**Comment by svanegas** [comment] 2015-07-31 13:56
I made the request, looked at the browser console and the network tab looks as follows:

![Network](http://i.imgur.com/xOwitGF.png)

Notice that the **Form Data** has this value:
`metadata=%7B%22color%22%3A%20%22blue%22%7D`

And if I click in *'view parsed'* it shows `metadata: {"color": "blue"}`

![Parsed](http://i.imgur.com/DPbaggN.png)

Also, the console throws the following error:

![Console](http://i.imgur.com/YhnIGNB.png)

**Comment by dblock** [comment] 2015-07-31 19:28
So this was form-encoded data, so it's different from what you supplied with CURL, which was properly encoded JSON data. This isn't the same thing.

Find out what the server is actually seeing, I am going to bet it's a string instead of a hash (it doesn't get parsed as JSON). Remove (relax) the `type: Hash` and print out what's inside `params`?

**Comment by svanegas** [comment] 2015-07-31 20:23
Okay, I removed the `type: Hash`and it accepted the parameter as a String. But if you write an invalid JSON you will obviously get an exception... So basically I think I need to handle the JSON conversion in my logic.

@dblock Thanks man.

**Comment by dblock** [comment] 2015-07-31 20:32
Yes. Basically this is not a bug, it's that Swagger UI sends data as a string "by design". If you want to be clever, you could introduce a JSON type that gets coerced, ie. converted by invoking `JSON.parse` (see how Grape does custom types in the README). This could be a good exercise and an interesting use case / blog post.

I am going to close this.

**Closed by dblock** 2015-07-31 20:32 UTC
Labels: bug?
