### ISSUE TITLE
Grape 0.9.0 and grape-swagger 0.9.0 incompatible

### ISSUE THREAD

**Issue by asinghrails** [tim-vandecasteele/grape-swagger#187] opened 2014-12-26 12:04 UTC
I am using Grape gem with rails app but I am getting below error when I call grape-swagger UI.

Error : Unable to read api 'users' from path https://appname.herokuapp.com/api/swagger_doc.json/users.json (server returned undefined)

Gem:: grape 0.9.0, grape-entity 0.4.4, grape-swagger 0.9.0, rails 4.1.6, rack-cors 0.2.9

Please help me

**Comment by aaronrenner** [comment] 2015-01-12 17:56
I ran into this issue as well. Here is a rails app that reproduces the problem:  https://github.com/aaronrenner/ember-contacts-backend-demo/tree/grape-swagger-issue. Since I'm continuing to work on the app, make sure to check out the grape-swagger-issue tag so you can reproduce it.

**Comment by dblock** [comment] 2015-01-13 14:07
@aaronrenner Just change https://github.com/aaronrenner/ember-contacts-backend-demo/blob/master/config/initializers/grape.rb#L1 from

```ruby
GrapeSwaggerRails.options.url = '/api/v1/swagger_doc.json'
```

to 

```ruby
GrapeSwaggerRails.options.url = '/api/v1/swagger_doc'
```

And everything will work.

Can everyone on this thread check this and confirm?

I changed https://github.com/tim-vandecasteele/grape-swagger/blob/master/UPGRADING.md.

**Comment by aaronrenner** [comment] 2015-01-13 17:32
That works. Thanks @dblock.

**Comment by nguyenchiencong** [comment] 2015-01-14 09:02
It works! Thanks @dblock.

**Comment by dblock** [comment] 2015-01-14 11:51
Closing this, thanks.

**Closed by dblock** 2015-01-14 11:51 UTC
Labels: confirmed bug

**Comment by railslauncher** [comment] 2015-02-19 17:35
@dblock It works.

Grape :green_heart: 
GrapeSwagger :green_heart:
GrapeSwaggerRails :green_heart: 
@dblock :green_heart:
